name: Build executable

on:
  push:
    branches: [main]

jobs:
  pyinstaller:
    runs-on: ubuntu-latest
    container:
      image: cheaterman/kivy-wine-pyinstaller-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install requirements
        run: wine pip install -r requirements.txt
      - name: Build executable
        run: wine pyinstaller --clean -y pyinstaller.spec
      - name: Rename artifact
        run: mv dist/app.exe ./slap.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: slap.exe
